defaults:
  - default_config_eval
visualize_interval: 0
exp_dir: ./outputs/custom_eval
dataset_name: custom
sample_len: 5
MODEL:
    model_name: DynamicStereoModel
    DynamicStereoModel:
        kernel_size: 4